version: "3.9"

services:
  # フロントエンド用コンテナ
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend:cached
      - node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true

  # バックエンド用コンテナ
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend

volumes:
  node_modules: