version: "3.9"

services:
  # TODO: DB用とバックエンド用コンテナを追加する

  # フロントエンド用コンテナ
  nuxt-app:
    build: ./frontend
    volumes:
      - ./frontend:/frontend:cached
      - node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
volumes:
  node_modules:
